spring.application.name=expense-tracker

# Server Port
server.port=3000

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://kishore_db_user:kishore31012008@cluster0.iyrjqfs.mongodb.net/expense_tracker_db?retryWrites=true&w=majority&appName=cluster0